# 拷贝脚本修改点 1 (一共 4 个): 重命名文件名. 主要把 release.3.0 相关修改为对应分支名, 后续步骤类似
# 拷贝脚本修改点 2 (一共 4 个)
name: 'build watch dog'
on:
  workflow_dispatch:
  push:
    branches:
      # 拷贝脚本修改点 3 (一共 4 个)
      - 'main'

env:
  # Semantic Versioning: https://semver.org/
  # 拷贝脚本修改点 4 (一共 4 个)
  major_version: "1"
  minor_version: "0"

jobs:
  cron-server:
    runs-on: self-hosted
    steps:
      - name: generate env variable
        run: |
          echo "registry_us=registry.cn-hangzhou.aliyuncs.com" >> $GITHUB_ENV
          echo "pool_cron_suffix=wsx124/public:${{ env.major_version }}.${{ env.minor_version }}.${{ github.run_number }}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Aliyun USA
        uses: docker/login-action@v1
        with:
          registry: ${{ env.registry_us }}
          username: wsxwsx124
          password: 123456wsx
      - name: Build and push watchdog
        id: docker_build_watchdog
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.registry_us }}/${{ env.pool_cron_suffix }}
      - name: Slack notification
        uses: tiloio/slack-webhook-action@v1.0.1
        with:
          slack_web_hook_url: 'https://hooks.slack.com/services/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'
          slack_json: '{
                           "username": "{{GITHUB_ACTOR}}",
                           "icon_url": "{{CUSTOM_AUTHOR_PICTURE}}",
                           "blocks": [
                               {
                                   "type": "section",
                                   "text": {
                                       "type": "mrkdwn",
                                       "text": ":hot_pepper: *watchdog 构建完毕*\n_{{CUSTOM_COMMIT_MSG}}_"
                                   }
                               },
                               {
                                   "type": "context",
                                   "elements": [
                                       {
                                           "type": "plain_text",
                                           "text": "cron: ${{ env.registry_us }}/${{ env.pool_cron_suffix }}"
                                       }
                                   ]
                               },
                               {
                                   "type": "context",
                                   "elements": [
                                       {
                                           "type": "plain_text",
                                           "text": "http: ${{ env.registry_us }}/${{ env.pool_http_suffix }}"
                                       }
                                   ]
                               }
                           ]
                       }'
